
name: RNM-gem CI

on:
  push:
  workflow_dispatch:
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # 5:23 am UTC (11:23pm MDT the day before) every weekday night in MDT
    - cron: '23 5 * * 2-6'

env:
  # This env var should enforce develop branch of all dependencies
  FAVOR_LOCAL_GEMS: true
  GEM_DEVELOPER_KEY: ${{ secrets.GEM_DEVELOPER_KEY }}

jobs:
  weeknight-tests:
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.9.0
    steps:
      - uses: actions/checkout@v4
      - name: set git config options
        shell: bash
        run: |
          git config --global --add safe.directory '*'
      - name: Update gems
        run: |
          ruby --version
          bundle install
          bundle update
      - name: Run Rspec
        run: bundle exec rspec
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        # Only upload if rspec fails
        if: ${{ failure() }}
        with:
          name: rspec_results
          path: |
            spec/test*/**
            # coverage/
          retention-days: 7 # save for 1 week before deleting
      # coveralls action docs: https://github.com/marketplace/actions/coveralls-github-action
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/lcov/urbanopt-rnm-us-gem.lcov"
